### PR TITLE
Add self update feature with GUI

### PR DESCRIPTION
**Pull request by kevinchua6**
Uses the https://github.com/creativeprojects/go-selfupdate package to detect updates and automatically self-updates when the app is started, prompting a restart.

Example:
Screenshot 2022-08-09 at 5 06 17 PM

Fixes https://github.com/Beebeeoii/lominus/issues/50

### CODE REVIEW

**Comment by Beebeeoii** [comment]
thanks for making this PR. looks good ! just some additional thoughts regarding this feature: would it be better to:

- have this checking for update run on daily cron instead of just on startup?
- have a check for update button somewhere (possibly in preferences) for users to check for updates immediately?
- have a "auto update checkbox" for users to indicate if they want the app to auto update?

**Comment by kevinchua6** [comment]
1) I think it's only necessary to do it on startup, because we need to restart the app anyway. It's also not a very costly operation in terms of time taken haha so I don't think there's much advantage of doing it on cron
2) I think that's a good idea! I'll implement this.
3) Good idea! I'll do this also

**Comment by Beebeeoii** [comment]
works fine on windows but something seems off when i tested this on kubuntu 22.04... looks like its something to do with permissions.

``` bash
[2022-08-09 22:47:51] FATAL - Error occurred while updating binary: open /usr/local/bin/.lominus.new: permission denied (/home/jiawei/Documents/lominus/internal/app/updater/updater.go:github.com/beebeeoii/lominus/internal/app/updater.DoSelfUpdate:43)
```

**Comment by Beebeeoii** [comment]
ill go ahead and close this PR as it is all merged into `feat-auto-update` and pending PR #81 into `development`. thank you so much !

**Pull request closed without merging**
